from pathlib import Path

from src.gcode.generator import GCodeGenerator, Stroke


def test_generate_contains_xdraw_setup(gcode_generator: GCodeGenerator, line_stroke: Stroke):
    lines = gcode_generator.generate([line_stroke])
    text = "\n".join(lines)

    assert "$H" in text
    assert "G92 X0 Y297 Z0" in text
    assert gcode_generator.config.pen_up_command in text
    assert gcode_generator.config.pen_down_command in text


def test_generate_draws_each_stroke(gcode_generator: GCodeGenerator, line_stroke: Stroke):
    lines = gcode_generator.generate([line_stroke, line_stroke], vary_speed=False)

    assert lines.count(gcode_generator.config.pen_down_command) == 2
    assert sum(1 for line in lines if line.startswith("G1 X")) == 2


def test_save_writes_gcode(
    tmp_path: Path,
    gcode_generator: GCodeGenerator,
    square_stroke: Stroke,
):
    output = tmp_path / "out.gcode"
    gcode_generator.save(gcode_generator.generate([square_stroke]), output)

    assert output.exists()
    assert output.read_text(encoding="utf-8").startswith("; Generated by pen_plotter")
