from __future__ import annotations

from scribing_plotter.config import PlotterConfig
from scribing_plotter.gcode import trajectory_to_gcode
from scribing_plotter.safety import validate_gcode


def _point(x: float, y: float, t: int, pen_state: int, pressure: float) -> dict[str, float | int]:
    return {"x": x, "y": y, "t": t, "pen_state": pen_state, "pressure": pressure}


def _simple_trajectory() -> list[dict[str, float | int]]:
    return [
        _point(0.0, 297.0, 0, 0, 0.0),
        _point(10.0, 280.0, 200, 0, 0.0),
        _point(10.0, 280.0, 200, 1, 0.9),
        _point(20.0, 280.0, 500, 1, 0.9),
        _point(20.0, 280.0, 500, 1, 0.45),
        _point(20.0, 280.0, 500, 0, 0.0),
    ]


def test_header_matches_machine_verified_skeleton() -> None:
    gcode = trajectory_to_gcode(_simple_trajectory())

    assert gcode[:6] == [
        "; Generated by scribing-plotter for xDraw A4",
        "$H",
        "G4 P1",
        "G92 X0 Y297 Z0",
        "G90",
        "G1G90 Z0.5 F5000",
    ]
    assert gcode[-1] == "G0 X5 Y292 F5000"
    assert gcode[-2] == "G1G90 Z0.5 F5000"


def test_pen_down_uses_z_command_and_g1_draw() -> None:
    gcode = trajectory_to_gcode(_simple_trajectory())

    assert "G1G90 Z3.5 F5000" in gcode  # pen down
    assert any(line.startswith("G1 X20.00 Y280.00") for line in gcode)  # draw move


def test_low_pressure_point_lifts_z_within_safe_band() -> None:
    config = PlotterConfig()
    gcode = trajectory_to_gcode(_simple_trajectory(), config)

    lift_lines = [line for line in gcode if line.startswith("G1 ") and " Z" in line]
    assert lift_lines, "expected a terminal lift G1 with explicit Z"
    z = float(lift_lines[-1].split(" Z")[1].split(" ")[0])
    assert config.finish_lift_z <= z < config.pen_down_z


def test_validate_gcode_passes_for_in_range_output() -> None:
    gcode = trajectory_to_gcode(_simple_trajectory())

    safety = validate_gcode(gcode)

    assert safety["ok"] is True
    assert safety["violations"] == []


def test_validate_gcode_flags_out_of_range() -> None:
    safety = validate_gcode(["G1 X999 Y10 F100000"])

    assert safety["ok"] is False
    assert any("x-out-of-range" in v for v in safety["violations"])
    assert any("feed-out-of-range" in v for v in safety["violations"])
