from __future__ import annotations

import math
from typing import Any, Sequence

from scribing_plotter.config import PlotterConfig


def trajectory_to_gcode(
    trajectory: Sequence[dict[str, Any]],
    config: PlotterConfig | None = None,
) -> list[str]:
    """Convert a paper-coordinate trajectory into xDraw A4 G-code.

    The emission skeleton (homing, ``G92`` paper origin, Z-axis pen control,
    travel/home moves) mirrors the machine-verified root generator. Per-point
    feed is derived from the trajectory timing and Z from the virtual pressure.
    """
    config = config or PlotterConfig()
    lines = _header(config)
    pen_down = False
    prev: dict[str, Any] | None = None

    for point in trajectory:
        x = float(point["x"])
        y = float(point["y"])
        down = int(point["pen_state"]) == 1

        if not down:
            if pen_down:
                lines.append(config.pen_up_command)
                pen_down = False
            if prev is None or (float(prev["x"]), float(prev["y"])) != (x, y):
                lines.append(f"G0 X{_fmt(x, config)} Y{_fmt(y, config)} F{config.travel_speed:.0f}")
            prev = point
            continue

        z = _pressure_to_z(float(point.get("pressure", 1.0)), config)
        if not pen_down:
            lines.append(f"G0 X{_fmt(x, config)} Y{_fmt(y, config)} F{config.travel_speed:.0f}")
            lines.append(config.pen_down_command)
            pen_down = True
            prev = point
            continue

        feed = _feed(prev, point, config) if prev is not None else config.min_draw_feed
        if z < config.pen_down_z - 1e-9:
            lines.append(
                f"G1 X{_fmt(x, config)} Y{_fmt(y, config)} Z{_fmt(z, config)} F{feed:.0f}"
            )
        else:
            lines.append(f"G1 X{_fmt(x, config)} Y{_fmt(y, config)} F{feed:.0f}")
        prev = point

    lines.extend(_footer(config))
    return lines


def _header(config: PlotterConfig) -> list[str]:
    return [
        "; Generated by scribing-plotter for xDraw A4",
        "$H",
        "G4 P1",
        f"G92 X0 Y{config.paper_height:.0f} Z0",
        "G90",
        config.pen_up_command,
    ]


def _footer(config: PlotterConfig) -> list[str]:
    return [
        config.pen_up_command,
        f"G0 X5 Y{config.paper_height - 5:.0f} F{config.travel_speed:.0f}",
    ]


def _pressure_to_z(pressure: float, config: PlotterConfig) -> float:
    """Map virtual pressure (1.0 = full contact) to a Z height within the safe band."""
    z = config.pen_down_z - (config.pen_down_z - config.finish_lift_z) * (1.0 - pressure)
    return min(config.pen_down_z, max(config.finish_lift_z, z))


def _feed(prev: dict[str, Any], curr: dict[str, Any], config: PlotterConfig) -> int:
    dt_ms = max(float(curr["t"]) - float(prev["t"]), 1.0)
    dist = math.hypot(float(curr["x"]) - float(prev["x"]), float(curr["y"]) - float(prev["y"]))
    feed = int(dist / (dt_ms / 1000.0) * 60.0)
    return max(config.min_draw_feed, min(config.max_draw_feed, feed))


def _fmt(value: float, config: PlotterConfig) -> str:
    return f"{value:.{config.decimal_places}f}"
