from __future__ import annotations

import math
import re
from dataclasses import asdict, dataclass
from typing import Any


Point = dict[str, Any]


@dataclass(frozen=True)
class XDrawExportConfig:
    paper_width: float = 210.0
    paper_height: float = 297.0
    pen_up_z: float = 0.5
    pen_down_z: float = 3.5
    finish_lift_z: float = 2.0
    z_feed: int = 5000
    travel_feed: int = 5000
    min_draw_feed: int = 300
    max_draw_feed: int = 1800
    decimal_places: int = 2


@dataclass(frozen=True)
class SafetyReport:
    ok: bool
    violations: tuple[str, ...]
    z_min: float
    z_max: float
    feed_min: int
    feed_max: int
    line_count: int

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["violations"] = list(self.violations)
        return data


def export_xdraw_gcode(
    trajectory: list[Point],
    config: XDrawExportConfig | None = None,
) -> list[str]:
    cfg = config or XDrawExportConfig()
    points = sorted(trajectory, key=lambda point: float(point.get("t", 0)))
    lines = [
        "; Generated by scribing-lab plotter-export for xDraw A4",
        "$H",
        "G4 P1",
        f"G92 X0 Y{cfg.paper_height:.0f} Z0",
        "G90",
        _z_command(cfg.pen_up_z, cfg),
    ]

    prev: Point | None = None
    pen_is_down = False
    for point in points:
        x = float(point.get("x", point.get("x_mm", 0.0)))
        y = float(point.get("y", point.get("y_mm", 0.0)))
        down = int(point.get("pen_state", 0)) == 1
        pressure = float(point.get("pressure", 0.0))

        if not down:
            if pen_is_down:
                lines.append(_z_command(cfg.pen_up_z, cfg))
                pen_is_down = False
            if prev is None or _xy(prev) != (x, y):
                lines.append(f"G0 X{_fmt(x, cfg)} Y{_fmt(y, cfg)} F{cfg.travel_feed}")
            prev = point
            continue

        if not pen_is_down:
            if prev is None or _xy(prev) != (x, y):
                lines.append(f"G0 X{_fmt(x, cfg)} Y{_fmt(y, cfg)} F{cfg.travel_feed}")
            lines.append(_z_command(_pressure_to_z(pressure, cfg), cfg))
            pen_is_down = True
            prev = point
            continue

        z = _pressure_to_z(pressure, cfg)
        feed = _feed_from_points(prev, point, cfg) if prev is not None else cfg.min_draw_feed
        lines.append(f"G1 X{_fmt(x, cfg)} Y{_fmt(y, cfg)} Z{_fmt(z, cfg)} F{feed}")
        prev = point

    lines.extend(
        [
            _z_command(cfg.pen_up_z, cfg),
            f"G0 X5 Y{cfg.paper_height - 5:.0f} F{cfg.travel_feed}",
        ]
    )
    return lines


def validate_xdraw_gcode(
    lines: list[str],
    config: XDrawExportConfig | None = None,
) -> SafetyReport:
    cfg = config or XDrawExportConfig()
    violations: list[str] = []
    z_values: list[float] = []
    feeds: list[int] = []

    text = "\n".join(lines)
    if "$H" not in text:
        violations.append("missing-home")
    if f"G92 X0 Y{cfg.paper_height:.0f} Z0" not in text:
        violations.append("missing-paper-origin")

    for line in lines:
        if line.startswith("G92"):
            continue
        x = _axis(line, "X")
        y = _axis(line, "Y")
        z = _axis(line, "Z")
        feed = _feed(line)
        if x is not None and not 0.0 <= x <= cfg.paper_width:
            violations.append(f"x-out-of-range:{x}")
        if y is not None and not 0.0 <= y <= cfg.paper_height:
            violations.append(f"y-out-of-range:{y}")
        if z is not None:
            z_values.append(z)
            if not cfg.pen_up_z <= z <= cfg.pen_down_z:
                violations.append(f"z-out-of-range:{z}")
        if feed is not None:
            feeds.append(feed)
            if feed <= 0 or feed > cfg.travel_feed:
                violations.append(f"feed-out-of-range:{feed}")

    return SafetyReport(
        ok=not violations,
        violations=tuple(violations),
        z_min=round(min(z_values), 4) if z_values else 0.0,
        z_max=round(max(z_values), 4) if z_values else 0.0,
        feed_min=min(feeds) if feeds else 0,
        feed_max=max(feeds) if feeds else 0,
        line_count=len(lines),
    )


def _pressure_to_z(pressure: float, cfg: XDrawExportConfig) -> float:
    p = max(0.0, min(1.0, pressure))
    z = cfg.finish_lift_z + (cfg.pen_down_z - cfg.finish_lift_z) * p
    return min(cfg.pen_down_z, max(cfg.finish_lift_z, z))


def _feed_from_points(prev: Point, curr: Point, cfg: XDrawExportConfig) -> int:
    dt_ms = max(float(curr.get("t", 0.0)) - float(prev.get("t", 0.0)), 1.0)
    px, py = _xy(prev)
    cx, cy = _xy(curr)
    dist = math.hypot(cx - px, cy - py)
    feed = int(dist / (dt_ms / 1000.0) * 60.0)
    return max(cfg.min_draw_feed, min(cfg.max_draw_feed, feed))


def _z_command(z: float, cfg: XDrawExportConfig) -> str:
    return f"G1G90 Z{_fmt(z, cfg)} F{cfg.z_feed}"


def _xy(point: Point) -> tuple[float, float]:
    return (
        float(point.get("x", point.get("x_mm", 0.0))),
        float(point.get("y", point.get("y_mm", 0.0))),
    )


def _fmt(value: float, cfg: XDrawExportConfig) -> str:
    return f"{value:.{cfg.decimal_places}f}"


def _axis(line: str, axis: str) -> float | None:
    match = re.search(rf"{axis}(-?\d+(?:\.\d+)?)", line)
    return float(match.group(1)) if match else None


def _feed(line: str) -> int | None:
    match = re.search(r"F(\d+)", line)
    return int(match.group(1)) if match else None
